//go:build go1.22

// Package redfish provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package redfish

import (
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BootSource.
const (
	BiosSetup    BootSource = "BiosSetup"
	Cd           BootSource = "Cd"
	Diags        BootSource = "Diags"
	Floppy       BootSource = "Floppy"
	Hdd          BootSource = "Hdd"
	None         BootSource = "None"
	Pxe          BootSource = "Pxe"
	RemoteDrive  BootSource = "RemoteDrive"
	SDCard       BootSource = "SDCard"
	UefiBootNext BootSource = "UefiBootNext"
	UefiHttp     BootSource = "UefiHttp"
	UefiShell    BootSource = "UefiShell"
	UefiTarget   BootSource = "UefiTarget"
	Usb          BootSource = "Usb"
	Utilities    BootSource = "Utilities"
)

// Defines values for BootSourceOverrideEnabled.
const (
	BootSourceOverrideEnabledContinuous BootSourceOverrideEnabled = "Continuous"
	BootSourceOverrideEnabledDisabled   BootSourceOverrideEnabled = "Disabled"
	BootSourceOverrideEnabledOnce       BootSourceOverrideEnabled = "Once"
)

// Defines values for ConnectedVia.
const (
	Applet       ConnectedVia = "Applet"
	NotConnected ConnectedVia = "NotConnected"
	Oem          ConnectedVia = "Oem"
	URI          ConnectedVia = "URI"
)

// Defines values for Health.
const (
	HealthCritical Health = "Critical"
	HealthOK       Health = "OK"
	HealthUnknown  Health = "Unknown"
	HealthWarning  Health = "Warning"
)

// Defines values for IDRACResetType.
const (
	IDRACResetTypeGracefulRestart IDRACResetType = "GracefulRestart"
)

// Defines values for IndicatorLED.
const (
	IndicatorLEDBlinking IndicatorLED = "Blinking"
	IndicatorLEDLit      IndicatorLED = "Lit"
	IndicatorLEDOff      IndicatorLED = "Off"
	IndicatorLEDUnknown  IndicatorLED = "Unknown"
)

// Defines values for ManagerType.
const (
	ManagerTypeAuxiliaryController  ManagerType = "AuxiliaryController"
	ManagerTypeBMC                  ManagerType = "BMC"
	ManagerTypeEnclosureManager     ManagerType = "EnclosureManager"
	ManagerTypeManagementController ManagerType = "ManagementController"
	ManagerTypeRackManager          ManagerType = "RackManager"
	ManagerTypeService              ManagerType = "Service"
)

// Defines values for PowerState.
const (
	Off         PowerState = "Off"
	On          PowerState = "On"
	PoweringOff PowerState = "PoweringOff"
	PoweringOn  PowerState = "PoweringOn"
)

// Defines values for ResetType.
const (
	ResetTypeForceOff         ResetType = "ForceOff"
	ResetTypeForceOn          ResetType = "ForceOn"
	ResetTypeForceRestart     ResetType = "ForceRestart"
	ResetTypeGracefulRestart  ResetType = "GracefulRestart"
	ResetTypeGracefulShutdown ResetType = "GracefulShutdown"
	ResetTypeNmi              ResetType = "Nmi"
	ResetTypeOn               ResetType = "On"
	ResetTypePowerCycle       ResetType = "PowerCycle"
	ResetTypePushPowerButton  ResetType = "PushPowerButton"
)

// Defines values for State.
const (
	StateAbsent             State = "Absent"
	StateDeferring          State = "Deferring"
	StateDisabled           State = "Disabled"
	StateEnabled            State = "Enabled"
	StateInTest             State = "InTest"
	StateQuiesced           State = "Quiesced"
	StateStandbyOffline     State = "StandbyOffline"
	StateStandbySpare       State = "StandbySpare"
	StateStarting           State = "Starting"
	StateUnavailableOffline State = "UnavailableOffline"
	StateUpdating           State = "Updating"
)

// Defines values for TaskState.
const (
	TaskStateCancelled   TaskState = "Cancelled"
	TaskStateCancelling  TaskState = "Cancelling"
	TaskStateCompleted   TaskState = "Completed"
	TaskStateException   TaskState = "Exception"
	TaskStateInterrupted TaskState = "Interrupted"
	TaskStateKilled      TaskState = "Killed"
	TaskStateNew         TaskState = "New"
	TaskStatePending     TaskState = "Pending"
	TaskStateRunning     TaskState = "Running"
	TaskStateService     TaskState = "Service"
	TaskStateStarting    TaskState = "Starting"
	TaskStateStopping    TaskState = "Stopping"
	TaskStateSuspended   TaskState = "Suspended"
)

// Defines values for TransferMethod.
const (
	Stream TransferMethod = "Stream"
	Upload TransferMethod = "Upload"
)

// Defines values for TransferProtocolType.
const (
	CIFS  TransferProtocolType = "CIFS"
	FTP   TransferProtocolType = "FTP"
	HTTP  TransferProtocolType = "HTTP"
	HTTPS TransferProtocolType = "HTTPS"
	NFS   TransferProtocolType = "NFS"
	SCP   TransferProtocolType = "SCP"
	SFTP  TransferProtocolType = "SFTP"
	TFTP  TransferProtocolType = "TFTP"
)

// Defines values for VolumeType.
const (
	Mirrored                 VolumeType = "Mirrored"
	NonRedundant             VolumeType = "NonRedundant"
	RawDevice                VolumeType = "RawDevice"
	SpannedMirrors           VolumeType = "SpannedMirrors"
	SpannedStripesWithParity VolumeType = "SpannedStripesWithParity"
	StripedWithParity        VolumeType = "StripedWithParity"
)

// Boot defines model for Boot.
type Boot struct {
	BootSourceOverrideEnabled                      *BootSourceOverrideEnabled `json:"BootSourceOverrideEnabled,omitempty"`
	BootSourceOverrideTarget                       *BootSource                `json:"BootSourceOverrideTarget,omitempty"`
	BootSourceOverrideTargetRedfishAllowableValues *[]BootSource              `json:"BootSourceOverrideTarget@Redfish.AllowableValues,omitempty"`
}

// BootSource defines model for BootSource.
type BootSource string

// BootSourceOverrideEnabled defines model for BootSourceOverrideEnabled.
type BootSourceOverrideEnabled string

// Collection A Collection of ComputerSystem resource instances.
type Collection struct {
	// OdataContext context
	OdataContext *string `json:"@odata.context,omitempty"`

	// OdataEtag etag
	OdataEtag *string `json:"@odata.etag,omitempty"`

	// OdataId id
	OdataId string `json:"@odata.id"`

	// OdataType type
	OdataType string `json:"@odata.type"`

	// Description description
	Description *string `json:"Description"`

	// Members Contains the members of this collection.
	Members *[]IdRef `json:"Members,omitempty"`

	// MembersOdataCount The number of items in a collection.
	MembersOdataCount *int `json:"Members@odata.count,omitempty"`

	// MembersOdataNextLink The URI to the resource containing the next set of partial members.
	MembersOdataNextLink *string `json:"Members@odata.nextLink,omitempty"`

	// Name The name of the resource.
	Name *string `json:"Name,omitempty"`
}

// ComputerSystem Root redfish path.
type ComputerSystem struct {
	// RedfishCopyright redfish copyright
	RedfishCopyright *string `json:"@Redfish.Copyright,omitempty"`

	// OdataContext The OData description of a payload.
	OdataContext *string `json:"@odata.context,omitempty"`

	// OdataId The unique identifier for a resource.
	OdataId *string `json:"@odata.id,omitempty"`

	// OdataType The type of a resource.
	OdataType *string                `json:"@odata.type,omitempty"`
	Actions   *ComputerSystemActions `json:"Actions,omitempty"`

	// Bios A reference to a resource.
	Bios *IdRef `json:"Bios,omitempty"`
	Boot *Boot  `json:"Boot,omitempty"`

	// EthernetInterfaces A reference to a resource.
	EthernetInterfaces *IdRef `json:"EthernetInterfaces,omitempty"`

	// Id The name of the resource.
	Id           *string       `json:"Id,omitempty"`
	IndicatorLED *IndicatorLED `json:"IndicatorLED,omitempty"`
	Links        *SystemLinks  `json:"Links,omitempty"`

	// Memory A reference to a resource.
	Memory        *IdRef         `json:"Memory,omitempty"`
	MemorySummary *MemorySummary `json:"MemorySummary,omitempty"`

	// Name The name of the resource.
	Name             *string           `json:"Name,omitempty"`
	PowerState       *PowerState       `json:"PowerState,omitempty"`
	ProcessorSummary *ProcessorSummary `json:"ProcessorSummary,omitempty"`

	// Processors A reference to a resource.
	Processors *IdRef `json:"Processors,omitempty"`

	// RedfishVersion redfish version
	RedfishVersion *string `json:"RedfishVersion,omitempty"`

	// SimpleStorage A reference to a resource.
	SimpleStorage *IdRef  `json:"SimpleStorage,omitempty"`
	Status        *Status `json:"Status,omitempty"`
	UUID          *string `json:"UUID,omitempty"`
}

// ComputerSystemReset defines model for ComputerSystemReset.
type ComputerSystemReset struct {
	ResetTypeRedfishAllowableValues *[]ResetType `json:"ResetType@Redfish.AllowableValues,omitempty"`

	// Target The unique identifier for a resource.
	Target *string `json:"target,omitempty"`
}

// ComputerSystemActions defines model for ComputerSystem_Actions.
type ComputerSystemActions struct {
	HashComputerSystemReset *ComputerSystemReset `json:"#ComputerSystem.Reset,omitempty"`
}

// ConnectedVia defines model for ConnectedVia.
type ConnectedVia string

// CreateVirtualDiskRequestBody defines model for CreateVirtualDiskRequestBody.
type CreateVirtualDiskRequestBody struct {
	Drives     []IdRef    `json:"Drives"`
	Name       string     `json:"Name"`
	VolumeType VolumeType `json:"VolumeType"`
}

// EjectMediaRequestBody defines model for EjectMediaRequestBody.
type EjectMediaRequestBody = map[string]interface{}

// FirmwareInventory defines model for FirmwareInventory.
type FirmwareInventory struct {
	// OdataId The unique identifier for a resource.
	OdataId *string `json:"@odata.id,omitempty"`
}

// Health defines model for Health.
type Health string

// IDRACResetRequestBody defines model for IDRACResetRequestBody.
type IDRACResetRequestBody struct {
	ResetType *IDRACResetType `json:"ResetType,omitempty"`
}

// IDRACResetType defines model for IDRACResetType.
type IDRACResetType string

// IndicatorLED defines model for IndicatorLED.
type IndicatorLED string

// InsertMediaRequestBody defines model for InsertMediaRequestBody.
type InsertMediaRequestBody struct {
	Image                string                `json:"Image"`
	Inserted             *bool                 `json:"Inserted,omitempty"`
	Password             *string               `json:"Password,omitempty"`
	TransferMethod       *TransferMethod       `json:"TransferMethod,omitempty"`
	TransferProtocolType *TransferProtocolType `json:"TransferProtocolType,omitempty"`
	UserName             *string               `json:"UserName,omitempty"`
	WriteProtected       *bool                 `json:"WriteProtected,omitempty"`
}

// Manager Redfish manager resource.
type Manager struct {
	// RedfishCopyright redfish copyright
	RedfishCopyright *string `json:"@Redfish.Copyright,omitempty"`

	// OdataContext The OData description of a payload.
	OdataContext *string `json:"@odata.context,omitempty"`

	// OdataId The unique identifier for a resource.
	OdataId *string `json:"@odata.id,omitempty"`

	// OdataType The type of a resource.
	OdataType *string `json:"@odata.type,omitempty"`
	DateTime  *string `json:"DateTime"`

	// DateTimeLocalOffset The time offset from UTC that the DateTime property is set to in format: +06:00 .
	DateTimeLocalOffset *string `json:"DateTimeLocalOffset"`

	// Description description
	Description *string `json:"Description"`

	// EthernetInterfaces A reference to a resource.
	EthernetInterfaces *IdRef  `json:"EthernetInterfaces,omitempty"`
	FirmwareVersion    *string `json:"FirmwareVersion"`

	// Id The name of the resource.
	Id          *string       `json:"Id,omitempty"`
	Links       *ManagerLinks `json:"Links,omitempty"`
	ManagerType *ManagerType  `json:"ManagerType,omitempty"`
	Model       *string       `json:"Model"`

	// Name The name of the resource.
	Name                  *string     `json:"Name,omitempty"`
	PowerState            *PowerState `json:"PowerState,omitempty"`
	ServiceEntryPointUUID *string     `json:"ServiceEntryPointUUID,omitempty"`
	Status                *Status     `json:"Status,omitempty"`
	UUID                  *string     `json:"UUID,omitempty"`

	// VirtualMedia A reference to a resource.
	VirtualMedia *IdRef `json:"VirtualMedia,omitempty"`
}

// ManagerLinks defines model for ManagerLinks.
type ManagerLinks struct {
	ManagerForChassis  *[]IdRef `json:"ManagerForChassis,omitempty"`
	ManagerForServers  *[]IdRef `json:"ManagerForServers,omitempty"`
	ManagerForSwitches *[]IdRef `json:"ManagerForSwitches,omitempty"`
	ManagerInChassis   *[]IdRef `json:"ManagerInChassis,omitempty"`
}

// ManagerType defines model for ManagerType.
type ManagerType string

// MemorySummary defines model for MemorySummary.
type MemorySummary struct {
	Status                         *Status  `json:"Status,omitempty"`
	TotalSystemMemoryGiB           *float32 `json:"TotalSystemMemoryGiB"`
	TotalSystemPersistentMemoryGiB *float32 `json:"TotalSystemPersistentMemoryGiB"`
}

// Message defines model for Message.
type Message struct {
	Message           *string   `json:"Message,omitempty"`
	MessageArgs       *[]string `json:"MessageArgs,omitempty"`
	MessageId         *string   `json:"MessageId,omitempty"`
	RelatedProperties *[]string `json:"RelatedProperties,omitempty"`
	Resolution        *string   `json:"Resolution,omitempty"`
	Severity          *string   `json:"Severity,omitempty"`
}

// Payload The HTTP and JSON payload details for this Task.
type Payload struct {
	// HttpHeaders This represents the HTTP headers used in the operation of this Task.
	HttpHeaders *[]string `json:"HttpHeaders,omitempty"`

	// HttpOperation The HTTP operation to perform to execute this Task.
	HttpOperation *string `json:"HttpOperation,omitempty"`

	// JsonBody This property contains the JSON payload to use in the execution of this Task.
	JsonBody *string `json:"JsonBody,omitempty"`

	// TargetUri The URI of the target for this task.
	TargetUri *string `json:"TargetUri,omitempty"`
}

// PowerState defines model for PowerState.
type PowerState string

// ProcessorSummary defines model for ProcessorSummary.
type ProcessorSummary struct {
	Count  *int    `json:"Count"`
	Status *Status `json:"Status,omitempty"`
}

// RedfishError Contains an error payload from a Redfish Service.
type RedfishError struct {
	Error RedfishErrorError `json:"error"`
}

// RedfishErrorError defines model for RedfishError_error.
type RedfishErrorError struct {
	MessageExtendedInfo *[]Message `json:"@Message.ExtendedInfo,omitempty"`
	Code                *string    `json:"code,omitempty"`
	Message             *string    `json:"message,omitempty"`
}

// ResetRequestBody defines model for ResetRequestBody.
type ResetRequestBody struct {
	ResetType *ResetType `json:"ResetType,omitempty"`
}

// ResetType defines model for ResetType.
type ResetType string

// Root Root redfish path.
type Root struct {
	// RedfishCopyright redfish copyright
	RedfishCopyright *string `json:"@Redfish.Copyright,omitempty"`

	// OdataId The unique identifier for a resource.
	OdataId *string `json:"@odata.id,omitempty"`

	// OdataType The type of a resource.
	OdataType *string `json:"@odata.type,omitempty"`

	// Id The name of the resource.
	Id *string `json:"Id,omitempty"`

	// Managers A reference to a resource.
	Managers *IdRef `json:"Managers,omitempty"`

	// Name The name of the resource.
	Name *string `json:"Name,omitempty"`

	// RedfishVersion redfish version
	RedfishVersion *string `json:"RedfishVersion,omitempty"`

	// Systems A reference to a resource.
	Systems *IdRef  `json:"Systems,omitempty"`
	UUID    *string `json:"UUID,omitempty"`
}

// SimpleUpdateRequestBody defines model for SimpleUpdateRequestBody.
type SimpleUpdateRequestBody struct {
	ImageURI             string                `json:"ImageURI"`
	Targets              *[]string             `json:"Targets,omitempty"`
	TransferProtocolType *TransferProtocolType `json:"TransferProtocolType,omitempty"`
}

// SoftwareInventory This schema defines an inventory of software components.
type SoftwareInventory struct {
	OdataContext           *string    `json:"@odata.context,omitempty"`
	OdataEtag              *string    `json:"@odata.etag,omitempty"`
	OdataId                *string    `json:"@odata.id,omitempty"`
	OdataType              *string    `json:"@odata.type,omitempty"`
	Description            *string    `json:"Description"`
	Id                     *string    `json:"Id,omitempty"`
	LowestSupportedVersion *string    `json:"LowestSupportedVersion"`
	Manufacturer           *string    `json:"Manufacturer"`
	Name                   *string    `json:"Name,omitempty"`
	RelatedItem            *[]IdRef   `json:"RelatedItem,omitempty"`
	RelatedItemOdataCount  *int       `json:"RelatedItem@odata.count"`
	ReleaseDate            *time.Time `json:"ReleaseDate"`
	SoftwareId             *string    `json:"SoftwareId,omitempty"`
	Status                 *Status    `json:"Status,omitempty"`
	UefiDevicePaths        *[]string  `json:"UefiDevicePaths,omitempty"`
	Updateable             *bool      `json:"Updateable"`
	Version                *string    `json:"Version"`
}

// State defines model for State.
type State string

// Status defines model for Status.
type Status struct {
	Health       *Health `json:"Health,omitempty"`
	HealthRollup *Health `json:"HealthRollup,omitempty"`
	State        *State  `json:"State,omitempty"`
}

// SystemLinks defines model for SystemLinks.
type SystemLinks struct {
	Chassis   *[]IdRef `json:"Chassis,omitempty"`
	ManagedBy *[]IdRef `json:"ManagedBy,omitempty"`
}

// Task This resource contains information about a specific Task scheduled by or being executed by a Redfish service's Task Service.
type Task struct {
	// OdataContext The OData description of a payload.
	OdataContext *string `json:"@odata.context,omitempty"`

	// OdataEtag The current ETag of the resource.
	OdataEtag *string `json:"@odata.etag,omitempty"`

	// OdataId The name of the resource.
	OdataId *string `json:"@odata.id,omitempty"`

	// OdataType The type of a resource.
	OdataType *string `json:"@odata.type,omitempty"`

	// Description description
	Description *string `json:"Description"`

	// EndTime The date-time stamp that the task was last completed.
	EndTime *string `json:"EndTime,omitempty"`

	// HidePayload Indicates that the contents of the Payload should be hidden from view after the Task has been created.  When set to True, the Payload object will not be returned on GET.
	HidePayload *bool `json:"HidePayload,omitempty"`

	// Id The name of the resource.
	Id *string `json:"Id,omitempty"`

	// Messages This is an array of messages associated with the task.
	Messages *[]Message `json:"Messages,omitempty"`

	// Name The name of the resource.
	Name *string `json:"Name,omitempty"`

	// Oem This is the manufacturer/provider specific extension moniker used to divide the Oem object into sections.
	Oem *string `json:"Oem,omitempty"`

	// Payload The HTTP and JSON payload details for this Task.
	Payload *Payload `json:"Payload,omitempty"`

	// StartTime The date-time stamp that the task was last started.
	StartTime *time.Time `json:"StartTime,omitempty"`

	// TaskMonitor The URI of the Task Monitor for this task.
	TaskMonitor *string    `json:"TaskMonitor,omitempty"`
	TaskState   *TaskState `json:"TaskState,omitempty"`
	TaskStatus  *Health    `json:"TaskStatus,omitempty"`
}

// TaskState defines model for TaskState.
type TaskState string

// TransferMethod defines model for TransferMethod.
type TransferMethod string

// TransferProtocolType defines model for TransferProtocolType.
type TransferProtocolType string

// UpdateService Redfish Update Service.
type UpdateService struct {
	// OdataContext The OData description of a payload.
	OdataContext *string `json:"@odata.context,omitempty"`

	// OdataId The unique identifier for a resource.
	OdataId *string `json:"@odata.id,omitempty"`

	// OdataType The type of a resource.
	OdataType *string               `json:"@odata.type,omitempty"`
	Actions   *UpdateServiceActions `json:"Actions,omitempty"`

	// Description description
	Description       *string            `json:"Description"`
	FirmwareInventory *FirmwareInventory `json:"FirmwareInventory,omitempty"`
	HttpPushUri       *string            `json:"HttpPushUri,omitempty"`

	// Id The name of the resource.
	Id *string `json:"Id,omitempty"`

	// Name The name of the resource.
	Name           *string `json:"Name,omitempty"`
	ServiceEnabled *bool   `json:"ServiceEnabled"`
}

// UpdateServiceActions defines model for UpdateService_Actions.
type UpdateServiceActions struct {
	HashUpdateServiceSimpleUpdate *VirtualMediaActionsVirtualMediaEjectMedia `json:"#UpdateService.SimpleUpdate,omitempty"`
	HashUpdateServiceStartUpdate  *VirtualMediaActionsVirtualMediaEjectMedia `json:"#UpdateService.StartUpdate,omitempty"`
}

// VirtualMedia Redfish virtual media resource for manager.
type VirtualMedia struct {
	// RedfishCopyright redfish copyright
	RedfishCopyright *string `json:"@Redfish.Copyright,omitempty"`

	// OdataContext The OData description of a payload.
	OdataContext *string `json:"@odata.context,omitempty"`

	// OdataId The unique identifier for a resource.
	OdataId *string `json:"@odata.id,omitempty"`

	// OdataType The type of a resource.
	OdataType    *string              `json:"@odata.type,omitempty"`
	Actions      *VirtualMediaActions `json:"Actions,omitempty"`
	ConnectedVia *ConnectedVia        `json:"ConnectedVia,omitempty"`

	// Description description
	Description *string `json:"Description"`

	// Id The name of the resource.
	Id         *string   `json:"Id,omitempty"`
	Image      *string   `json:"Image"`
	ImageName  *string   `json:"ImageName"`
	Inserted   *bool     `json:"Inserted"`
	MediaTypes *[]string `json:"MediaTypes,omitempty"`

	// Name The name of the resource.
	Name                 *string               `json:"Name,omitempty"`
	Password             *string               `json:"Password"`
	TransferMethod       *TransferMethod       `json:"TransferMethod,omitempty"`
	TransferProtocolType *TransferProtocolType `json:"TransferProtocolType,omitempty"`
	UserName             *string               `json:"UserName"`
	WriteProtected       *bool                 `json:"WriteProtected"`
}

// VirtualMediaActions defines model for VirtualMedia_Actions.
type VirtualMediaActions struct {
	HashVirtualMediaEjectMedia  *VirtualMediaActionsVirtualMediaEjectMedia `json:"#VirtualMedia.EjectMedia,omitempty"`
	HashVirtualMediaInsertMedia *VirtualMediaActionsVirtualMediaEjectMedia `json:"#VirtualMedia.InsertMedia,omitempty"`
}

// VirtualMediaActionsVirtualMediaEjectMedia defines model for VirtualMedia_Actions__VirtualMedia_EjectMedia.
type VirtualMediaActionsVirtualMediaEjectMedia struct {
	// Target The unique identifier for a resource.
	Target *string `json:"target,omitempty"`
}

// VolumeType defines model for VolumeType.
type VolumeType string

// IdRef A reference to a resource.
type IdRef struct {
	// OdataId The unique identifier for a resource.
	OdataId *string `json:"@odata.id,omitempty"`
}

// FirmwareInventoryDownloadImageMultipartBody defines parameters for FirmwareInventoryDownloadImage.
type FirmwareInventoryDownloadImageMultipartBody struct {
	SoftwareImage *openapi_types.File `json:"softwareImage,omitempty"`
}

// ResetIdracJSONRequestBody defines body for ResetIdrac for application/json ContentType.
type ResetIdracJSONRequestBody = IDRACResetRequestBody

// EjectVirtualMediaJSONRequestBody defines body for EjectVirtualMedia for application/json ContentType.
type EjectVirtualMediaJSONRequestBody = EjectMediaRequestBody

// InsertVirtualMediaJSONRequestBody defines body for InsertVirtualMedia for application/json ContentType.
type InsertVirtualMediaJSONRequestBody = InsertMediaRequestBody

// ResetSystemJSONRequestBody defines body for ResetSystem for application/json ContentType.
type ResetSystemJSONRequestBody = ResetRequestBody

// CreateVirtualDiskJSONRequestBody defines body for CreateVirtualDisk for application/json ContentType.
type CreateVirtualDiskJSONRequestBody = CreateVirtualDiskRequestBody

// SetSystemJSONRequestBody defines body for SetSystem for application/json ContentType.
type SetSystemJSONRequestBody = ComputerSystem

// UpdateServiceSimpleUpdateJSONRequestBody defines body for UpdateServiceSimpleUpdate for application/json ContentType.
type UpdateServiceSimpleUpdateJSONRequestBody = SimpleUpdateRequestBody

// FirmwareInventoryDownloadImageMultipartRequestBody defines body for FirmwareInventoryDownloadImage for multipart/formdata ContentType.
type FirmwareInventoryDownloadImageMultipartRequestBody FirmwareInventoryDownloadImageMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /redfish/v1)
	GetRoot(w http.ResponseWriter, r *http.Request)

	// (GET /redfish/v1/Managers)
	ListManagers(w http.ResponseWriter, r *http.Request)

	// (POST /redfish/v1/Managers/iDRAC.Embedded.1/Actions/Manager.Reset)
	ResetIdrac(w http.ResponseWriter, r *http.Request)

	// (GET /redfish/v1/Managers/{managerId})
	GetManager(w http.ResponseWriter, r *http.Request, managerId string)

	// (GET /redfish/v1/Managers/{managerId}/VirtualMedia)
	ListManagerVirtualMedia(w http.ResponseWriter, r *http.Request, managerId string)

	// (GET /redfish/v1/Managers/{managerId}/VirtualMedia/{virtualMediaId})
	GetManagerVirtualMedia(w http.ResponseWriter, r *http.Request, managerId string, virtualMediaId string)

	// (POST /redfish/v1/Managers/{managerId}/VirtualMedia/{virtualMediaId}/Actions/VirtualMedia.EjectMedia)
	EjectVirtualMedia(w http.ResponseWriter, r *http.Request, managerId string, virtualMediaId string)

	// (POST /redfish/v1/Managers/{managerId}/VirtualMedia/{virtualMediaId}/Actions/VirtualMedia.InsertMedia)
	InsertVirtualMedia(w http.ResponseWriter, r *http.Request, managerId string, virtualMediaId string)

	// (GET /redfish/v1/Systems)
	ListSystems(w http.ResponseWriter, r *http.Request)

	// (POST /redfish/v1/Systems/{ComputerSystemId}/Actions/ComputerSystem.Reset)
	ResetSystem(w http.ResponseWriter, r *http.Request, computerSystemId string)

	// (DELETE /redfish/v1/Systems/{ComputerSystemId}/Storage/Volumes/{StorageId})
	DeleteVirtualdisk(w http.ResponseWriter, r *http.Request, computerSystemId string, storageId string)

	// (GET /redfish/v1/Systems/{ComputerSystemId}/Storage/{StorageControllerId}/Volumes)
	GetVolumes(w http.ResponseWriter, r *http.Request, computerSystemId string, storageControllerId string)

	// (POST /redfish/v1/Systems/{ComputerSystemId}/Storage/{StorageControllerId}/Volumes)
	CreateVirtualDisk(w http.ResponseWriter, r *http.Request, computerSystemId string, storageControllerId string)

	// (GET /redfish/v1/Systems/{ComputerSystemId})
	GetSystem(w http.ResponseWriter, r *http.Request, ComputerSystemId string)

	// (PATCH /redfish/v1/Systems/{ComputerSystemId})
	SetSystem(w http.ResponseWriter, r *http.Request, ComputerSystemId string)

	// (GET /redfish/v1/TaskService/Tasks)
	GetTaskList(w http.ResponseWriter, r *http.Request)

	// (GET /redfish/v1/TaskService/Tasks/{taskId})
	GetTask(w http.ResponseWriter, r *http.Request, taskId string)

	// (GET /redfish/v1/UpdateService)
	UpdateService(w http.ResponseWriter, r *http.Request)

	// (POST /redfish/v1/UpdateService/Actions/UpdateService.SimpleUpdate)
	UpdateServiceSimpleUpdate(w http.ResponseWriter, r *http.Request)

	// (GET /redfish/v1/UpdateService/FirmwareInventory)
	FirmwareInventory(w http.ResponseWriter, r *http.Request)

	// (POST /redfish/v1/UpdateService/FirmwareInventory)
	FirmwareInventoryDownloadImage(w http.ResponseWriter, r *http.Request)

	// (GET /redfish/v1/UpdateService/FirmwareInventory/{softwareId})
	GetSoftwareInventory(w http.ResponseWriter, r *http.Request, softwareId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetRoot operation middleware
func (siw *ServerInterfaceWrapper) GetRoot(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoot(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListManagers operation middleware
func (siw *ServerInterfaceWrapper) ListManagers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListManagers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetIdrac operation middleware
func (siw *ServerInterfaceWrapper) ResetIdrac(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetIdrac(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetManager operation middleware
func (siw *ServerInterfaceWrapper) GetManager(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "managerId" -------------
	var managerId string

	err = runtime.BindStyledParameterWithOptions("simple", "managerId", r.PathValue("managerId"), &managerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "managerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetManager(w, r, managerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListManagerVirtualMedia operation middleware
func (siw *ServerInterfaceWrapper) ListManagerVirtualMedia(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "managerId" -------------
	var managerId string

	err = runtime.BindStyledParameterWithOptions("simple", "managerId", r.PathValue("managerId"), &managerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "managerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListManagerVirtualMedia(w, r, managerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetManagerVirtualMedia operation middleware
func (siw *ServerInterfaceWrapper) GetManagerVirtualMedia(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "managerId" -------------
	var managerId string

	err = runtime.BindStyledParameterWithOptions("simple", "managerId", r.PathValue("managerId"), &managerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "managerId", Err: err})
		return
	}

	// ------------- Path parameter "virtualMediaId" -------------
	var virtualMediaId string

	err = runtime.BindStyledParameterWithOptions("simple", "virtualMediaId", r.PathValue("virtualMediaId"), &virtualMediaId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "virtualMediaId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetManagerVirtualMedia(w, r, managerId, virtualMediaId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EjectVirtualMedia operation middleware
func (siw *ServerInterfaceWrapper) EjectVirtualMedia(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "managerId" -------------
	var managerId string

	err = runtime.BindStyledParameterWithOptions("simple", "managerId", r.PathValue("managerId"), &managerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "managerId", Err: err})
		return
	}

	// ------------- Path parameter "virtualMediaId" -------------
	var virtualMediaId string

	err = runtime.BindStyledParameterWithOptions("simple", "virtualMediaId", r.PathValue("virtualMediaId"), &virtualMediaId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "virtualMediaId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EjectVirtualMedia(w, r, managerId, virtualMediaId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InsertVirtualMedia operation middleware
func (siw *ServerInterfaceWrapper) InsertVirtualMedia(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "managerId" -------------
	var managerId string

	err = runtime.BindStyledParameterWithOptions("simple", "managerId", r.PathValue("managerId"), &managerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "managerId", Err: err})
		return
	}

	// ------------- Path parameter "virtualMediaId" -------------
	var virtualMediaId string

	err = runtime.BindStyledParameterWithOptions("simple", "virtualMediaId", r.PathValue("virtualMediaId"), &virtualMediaId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "virtualMediaId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InsertVirtualMedia(w, r, managerId, virtualMediaId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSystems operation middleware
func (siw *ServerInterfaceWrapper) ListSystems(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSystems(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetSystem operation middleware
func (siw *ServerInterfaceWrapper) ResetSystem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "ComputerSystemId" -------------
	var computerSystemId string

	err = runtime.BindStyledParameterWithOptions("simple", "ComputerSystemId", r.PathValue("ComputerSystemId"), &computerSystemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ComputerSystemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetSystem(w, r, computerSystemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteVirtualdisk operation middleware
func (siw *ServerInterfaceWrapper) DeleteVirtualdisk(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "ComputerSystemId" -------------
	var computerSystemId string

	err = runtime.BindStyledParameterWithOptions("simple", "ComputerSystemId", r.PathValue("ComputerSystemId"), &computerSystemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ComputerSystemId", Err: err})
		return
	}

	// ------------- Path parameter "StorageId" -------------
	var storageId string

	err = runtime.BindStyledParameterWithOptions("simple", "StorageId", r.PathValue("StorageId"), &storageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "StorageId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteVirtualdisk(w, r, computerSystemId, storageId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVolumes operation middleware
func (siw *ServerInterfaceWrapper) GetVolumes(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "ComputerSystemId" -------------
	var computerSystemId string

	err = runtime.BindStyledParameterWithOptions("simple", "ComputerSystemId", r.PathValue("ComputerSystemId"), &computerSystemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ComputerSystemId", Err: err})
		return
	}

	// ------------- Path parameter "StorageControllerId" -------------
	var storageControllerId string

	err = runtime.BindStyledParameterWithOptions("simple", "StorageControllerId", r.PathValue("StorageControllerId"), &storageControllerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "StorageControllerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVolumes(w, r, computerSystemId, storageControllerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateVirtualDisk operation middleware
func (siw *ServerInterfaceWrapper) CreateVirtualDisk(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "ComputerSystemId" -------------
	var computerSystemId string

	err = runtime.BindStyledParameterWithOptions("simple", "ComputerSystemId", r.PathValue("ComputerSystemId"), &computerSystemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ComputerSystemId", Err: err})
		return
	}

	// ------------- Path parameter "StorageControllerId" -------------
	var storageControllerId string

	err = runtime.BindStyledParameterWithOptions("simple", "StorageControllerId", r.PathValue("StorageControllerId"), &storageControllerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "StorageControllerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateVirtualDisk(w, r, computerSystemId, storageControllerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSystem operation middleware
func (siw *ServerInterfaceWrapper) GetSystem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "ComputerSystemId" -------------
	var ComputerSystemId string

	err = runtime.BindStyledParameterWithOptions("simple", "ComputerSystemId", r.PathValue("ComputerSystemId"), &ComputerSystemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ComputerSystemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSystem(w, r, ComputerSystemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetSystem operation middleware
func (siw *ServerInterfaceWrapper) SetSystem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "ComputerSystemId" -------------
	var ComputerSystemId string

	err = runtime.BindStyledParameterWithOptions("simple", "ComputerSystemId", r.PathValue("ComputerSystemId"), &ComputerSystemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ComputerSystemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetSystem(w, r, ComputerSystemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTaskList operation middleware
func (siw *ServerInterfaceWrapper) GetTaskList(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTaskList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTask operation middleware
func (siw *ServerInterfaceWrapper) GetTask(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "taskId" -------------
	var taskId string

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", r.PathValue("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTask(w, r, taskId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateService operation middleware
func (siw *ServerInterfaceWrapper) UpdateService(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateService(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateServiceSimpleUpdate operation middleware
func (siw *ServerInterfaceWrapper) UpdateServiceSimpleUpdate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateServiceSimpleUpdate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FirmwareInventory operation middleware
func (siw *ServerInterfaceWrapper) FirmwareInventory(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FirmwareInventory(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FirmwareInventoryDownloadImage operation middleware
func (siw *ServerInterfaceWrapper) FirmwareInventoryDownloadImage(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FirmwareInventoryDownloadImage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSoftwareInventory operation middleware
func (siw *ServerInterfaceWrapper) GetSoftwareInventory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "softwareId" -------------
	var softwareId string

	err = runtime.BindStyledParameterWithOptions("simple", "softwareId", r.PathValue("softwareId"), &softwareId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "softwareId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSoftwareInventory(w, r, softwareId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET /redfish/v1", wrapper.GetRoot)
	m.HandleFunc("GET /redfish/v1/Managers", wrapper.ListManagers)
	m.HandleFunc("POST /redfish/v1/Managers/iDRAC.Embedded.1/Actions/Manager.Reset", wrapper.ResetIdrac)
	m.HandleFunc("GET /redfish/v1/Managers/{managerId}", wrapper.GetManager)
	m.HandleFunc("GET /redfish/v1/Managers/{managerId}/VirtualMedia", wrapper.ListManagerVirtualMedia)
	m.HandleFunc("GET /redfish/v1/Managers/{managerId}/VirtualMedia/{virtualMediaId}", wrapper.GetManagerVirtualMedia)
	m.HandleFunc("POST /redfish/v1/Managers/{managerId}/VirtualMedia/{virtualMediaId}/Actions/VirtualMedia.EjectMedia", wrapper.EjectVirtualMedia)
	m.HandleFunc("POST /redfish/v1/Managers/{managerId}/VirtualMedia/{virtualMediaId}/Actions/VirtualMedia.InsertMedia", wrapper.InsertVirtualMedia)
	m.HandleFunc("GET /redfish/v1/Systems", wrapper.ListSystems)
	m.HandleFunc("POST /redfish/v1/Systems/{ComputerSystemId}/Actions/ComputerSystem.Reset", wrapper.ResetSystem)
	m.HandleFunc("DELETE /redfish/v1/Systems/{ComputerSystemId}/Storage/Volumes/{StorageId}", wrapper.DeleteVirtualdisk)
	m.HandleFunc("GET /redfish/v1/Systems/{ComputerSystemId}/Storage/{StorageControllerId}/Volumes", wrapper.GetVolumes)
	m.HandleFunc("POST /redfish/v1/Systems/{ComputerSystemId}/Storage/{StorageControllerId}/Volumes", wrapper.CreateVirtualDisk)
	m.HandleFunc("GET /redfish/v1/Systems/{ComputerSystemId}", wrapper.GetSystem)
	m.HandleFunc("PATCH /redfish/v1/Systems/{ComputerSystemId}", wrapper.SetSystem)
	m.HandleFunc("GET /redfish/v1/TaskService/Tasks", wrapper.GetTaskList)
	m.HandleFunc("GET /redfish/v1/TaskService/Tasks/{taskId}", wrapper.GetTask)
	m.HandleFunc("GET /redfish/v1/UpdateService", wrapper.UpdateService)
	m.HandleFunc("POST /redfish/v1/UpdateService/Actions/UpdateService.SimpleUpdate", wrapper.UpdateServiceSimpleUpdate)
	m.HandleFunc("GET /redfish/v1/UpdateService/FirmwareInventory", wrapper.FirmwareInventory)
	m.HandleFunc("POST /redfish/v1/UpdateService/FirmwareInventory", wrapper.FirmwareInventoryDownloadImage)
	m.HandleFunc("GET /redfish/v1/UpdateService/FirmwareInventory/{softwareId}", wrapper.GetSoftwareInventory)

	return m
}
